#! /bin/bash

# sortfsa [options]

# -f the number of bases printed per line in 
#    fasta format (default: -f 70)
# -i fasta file to sort

# Two examples:
# $ cat Pa_can008.fsa | ./sortfsa
# $ ./sortfsa -i Pa_can008.fsa

f=70
i="stdin"
while getopts "f:i:" opt; do
    case $opt in
	f) f=${OPTARG}
	    ;;
	i) i=${OPTARG}
	    ;;
    esac
done

function fasta2line() {
    
    num=0
    while read line; do
	if [ $num == 0 ]; then
	    id=$line
	    string=""
	    num=1
	else
	    if [ ${line:0:1} == ">" ]; then
		echo $id" "$string
		string=""
		id=$line
	    else
		string=$string${line%"\n"}
	    fi
	fi
    done
    echo $id" "$string    
}

if [ $i == "stdin" ]; then
    while read input; do echo $input; done | fasta2line | sort | awk ' { print $1"\n"$2 }' | fold -w $f
else
    cat $i | fasta2line | sort | awk ' { print $1"\n"$2 }' | fold -w $f
fi
